# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matmulti <- function(m1, m2) {
    .Call(`_lmcpp_matmulti`, m1, m2)
}

matvecmulti <- function(m, v) {
    .Call(`_lmcpp_matvecmulti`, m, v)
}

arma2mat <- function(x) {
    .Call(`_lmcpp_arma2mat`, x)
}

arma2vec <- function(x) {
    .Call(`_lmcpp_arma2vec`, x)
}

lmCpp <- function(x, y) {
    .Call(`_lmcpp_lmCpp`, x, y)
}

